development:
  github_client_id: '09118830e21db2f8968c'
  github_client_secret: '48258cd47bd8bdfc18b8d13f1c08a23abd733865'
  github_auth_url: 'https://github.com/login/oauth/access_token'
  github_get_info: 'https://api.github.com/users'
  gitlab_client_id: 'ed8fb518dbfca5f406e0d321993705923b37963770c2d2c3077cc84bb4796dab'
  gitlab_client_secret: 'd9cf8731fa0e43eb7dd7b68b8d11b5b60d63f4eae76f433f72cf0db81bfd3554'
  gitlab_callback_url: 'http://localhost:3000/auth_redirect.html'
  gitlab_auth_url: 'https://gitlab.com/oauth/token'
  bitbucket_client_id: 'a4rVkvUut6Dx5pAzdw'
  bitbucket_client_secret: 'twrzaLVm7w2xQrtUxdrFqVDn53jDgD7L'
  bitbucket_callback_url: 'http://localhost:3000/auth_redirect.html'
  bitbucket_auth_url: 'https://bitbucket.org/site/oauth2/access_token'
